### ISSUE TITLE
Static analysis: FindBugs, best practices

### ISSUE THREAD

**Issue by Karm** [Karm/PA193_SixEleven_parser_critique#6]
The project uses discouraged constructs such as numerous ```System.out.println(...)``` instead of proper StringBuffers, unchecked conversions, all things that should be caught by code style plugins of [FindBugs](http://findbugs.sourceforge.net/). Furthermore, it appears hard coded constants are very much prevalent throughout the project; it should be verified whether such usage is really justified.
# Call to action
 * Inspect and report
 * Run FindBugs and sift through false positives, report

**Comment by RichardKalinec** [comment]
This issue was solved; this led to opening of the following isues in the original repository:
[FindBugs - Bad practice: Dubious method used - method invokes System.exit(...)](https://github.com/dogukanucak/PA193_test_parser_SixEleven/issues/23)
[FindBugs - Internationalization: Dubious method used - reliance on default encoding](https://github.com/dogukanucak/PA193_test_parser_SixEleven/issues/24)
[FindBugs - Performance: Method concatenates strings using + in a loop](https://github.com/dogukanucak/PA193_test_parser_SixEleven/issues/25)
[FindBugs - Security: Unencrypted Socket](https://github.com/dogukanucak/PA193_test_parser_SixEleven/issues/26)
