### ISSUE TITLE
Static analysis: Compare analysis of FindBugs with PMD

### ISSUE THREAD

**Issue by Karm** [Karm/PA193_SixEleven_parser_critique#8]
It might prove being worth the candle to run [PMD](https://pmd.github.io/pmd-5.8.1/usage/installing.html) alongside [FindBugs](http://findbugs.sourceforge.net/) to find out more about the possible bugs in the project.
# Call to action
 * Execute PMD, report
 * Execute FindBugs, report

**Comment by RichardKalinec** [comment]
This issue has been solved; this resulted in the opening of the following issues in the original repository:
[PMD: Unused inports](https://github.com/dogukanucak/PA193_test_parser_SixEleven/issues)
[PMD: Private fields initialized only in the declaration or constructor of a class can be marked as final](https://github.com/dogukanucak/PA193_test_parser_SixEleven/issues/28)
[SimpleDateFormat object is instantiated without specifying a Locale](https://github.com/dogukanucak/PA193_test_parser_SixEleven/issues/29)
[PMD: the ArrayList implementation types is used instead of the interface](https://github.com/dogukanucak/PA193_test_parser_SixEleven/issues/30)
